#define BAROMETER_UPDATE_INTERVAL 1.0
#define BAROMETER_ENABLED 1
#define BATTERY_ENABLED 1
#define BATTERY_UPDATE_INTERVAL 0.1                          
#define BATTERY_CELLS 1                                      
#define BATTERY_MIN_LEVEL 3400 * BATTERY_CELLS               
#define BATTERY_MAX_LEVEL 4200 * BATTERY_CELLS               
#define BATTERY_DISARMED_VOLTAGE_THRESHOLD BATTERY_MIN_LEVEL 
#define BATTERY_DISARMED_CURRENT_THRESHOLD_MIN 10            
#define BATTERY_DISARMED_CURRENT_THRESHOLD_MAX 15000         
#define BATTERY_MAVLINK_STATUS_LOW 3500 * BATTERY_CELLS
#define BATTERY_MAVLINK_STATUS_CRITICAL 3300 * BATTERY_CELLS
#define BATTERY_MAVLINK_STATUS_EMERGENCY BATTERY_MIN_LEVEL
#define UWB_SPACING 0.099394;
